import React, { useState, useEffect } from 'react';
import { Estimate, CustomCost } from './types';
import Dashboard from './pages/Dashboard';
import NewEstimate from './pages/NewEstimate';
import EstimateResult from './pages/EstimateResult';
import Header from './components/Header';
import { fetchEstimates } from './services/estimateService';
import Spinner from './components/Spinner';

type Page = 'dashboard' | 'new_estimate' | 'estimate_result';

const App: React.FC = () => {
  const [currentPage, setCurrentPage] = useState<Page>('dashboard');
  const [activeEstimate, setActiveEstimate] = useState<Estimate | null>(null);
  const [estimates, setEstimates] = useState<Estimate[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [customCosts, setCustomCosts] = useState<CustomCost[]>([
    { id: 'waiter', name: 'Diária Garçom', cost: 150 },
    { id: 'cook', name: 'Diária Cozinheira', cost: 200 },
    { id: 'marketing', name: 'Marketing e Foto', cost: 250 },
  ]);

  // Função para carregar orçamentos
  const loadEstimates = async () => {
    setIsLoading(true);
    try {
      // NOTE: This will currently fail if the user is not authenticated.
      // We will implement proper auth later. For now, we assume a session exists 
      // or handle the error gracefully.
      const fetchedEstimates = await fetchEstimates();
      setEstimates(fetchedEstimates);
    } catch (error) {
      console.error("Failed to fetch estimates:", error);
      // Optionally show a toast error here
    } finally {
      setIsLoading(false);
    }
  };

  useEffect(() => {
    loadEstimates();
  }, []);

  const handleCreateNewEstimate = () => {
    setActiveEstimate(null);
    setCurrentPage('new_estimate');
  };
  
  const handleViewEstimate = (estimate: Estimate) => {
    setActiveEstimate(estimate);
    setCurrentPage('estimate_result');
  };
  
  const handleShowDashboard = () => {
    setActiveEstimate(null);
    setCurrentPage('dashboard');
    // Reload estimates when returning to dashboard to ensure fresh data
    loadEstimates(); 
  };

  const handleEstimateGenerated = (estimate: Estimate) => {
    // The estimate generated by GeminiService is saved in NewEstimate/EstimateResult 
    // and should already be in the DB or handled by the next step.
    // For now, we rely on the next step (saving) to update the list.
    setActiveEstimate(estimate);
    setCurrentPage('estimate_result');
  };

  const renderPage = () => {
    if (isLoading) {
        return (
            <div className="flex justify-center items-center h-96">
                <Spinner message="Carregando orçamentos..." />
            </div>
        );
    }

    switch (currentPage) {
      case 'new_estimate':
        return <NewEstimate onEstimateGenerated={handleEstimateGenerated} customCosts={customCosts} />;
      case 'estimate_result':
        // Pass loadEstimates to allow saving/updating the list after changes
        return activeEstimate ? <EstimateResult estimate={activeEstimate} onEstimateSaved={loadEstimates} /> : <Dashboard estimates={estimates} onCreateNew={handleCreateNewEstimate} onView={handleViewEstimate} customCosts={customCosts} onCustomCostsChange={setCustomCosts} />;
      case 'dashboard':
      default:
        return <Dashboard estimates={estimates} onCreateNew={handleCreateNewEstimate} onView={handleViewEstimate} customCosts={customCosts} onCustomCostsChange={setCustomCosts} />;
    }
  };

  return (
    <div className="min-h-screen bg-slate-100 font-sans">
      <Header onLogoClick={handleShowDashboard} />
      <main className="p-4 sm:p-6 md:p-8">
        {renderPage()}
      </main>
    </div>
  );
};

export default App;